{{- if and (not .Values.secretRef.name) .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "agentic-ai.secretName" . }}
  labels:
    {{- include "agentic-ai.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $val := .Values.secret.data }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
{{- end }}
