version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      PORT: "3000"
      MONGODB_URI: "your_production_mongodb_connection_string"
      GOOGLE_AI_API_KEY: "your_google_ai_api_key"
      AI_INSTRUCTIONS: "Your system instructions for Gemini AI"
      NEWS_API_KEY: "your_newsapi_key"
      CRAWL_URLS: "https://www.whitehouse.gov/briefing-room/,https://www.congress.gov/,https://www.state.gov/press-releases/,https://www.bbc.com/news,https://www.nytimes.com/"
    restart: unless-stopped
